HomeTask/Models/Storage.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace HomeTask.Models
{
    public class Storage
    {
        public int StorageId { get; set; }
        public string StorageName { get; set; }
        public string Address { get; set; }
        
        public List<Product> Products { get; set; } = new List<Product>();
        
        public List<ProductsInStock> ProductsInStocks { get; set; } = new List<ProductsInStock>();

    }
}

HomeTask/ViewModels/CalculateSumViewModel.cs
using HomeTask.Models;

namespace HomeTask.ViewModels
{
    public class CalculateSumViewModel
    {
        public decimal CurrencyId { get; set; }
        public decimal Sum { get; set; }
    }
}

HomeTask/ViewModels/StorageView.cs
using Microsoft.AspNetCore.Mvc;

namespace HomeTask.ViewModels
{
    public class StorageView
    {
        [Remote("VerifyStorageName", "Validator", ErrorMessage = "Storage already exist")]
        public string StorageName { get; set; }
        public string Address { get; set; }
    }
}

HomeTask/Controllers/ProductsInStocksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeTask.Models;

namespace HomeTask.Controllers
{
    public class ProductsInStocksController : Controller
    {
        private readonly HomeTaskContext _context;

        public ProductsInStocksController(HomeTaskContext context)
        {
            _context = context;
        }

        // GET: ProductsInStocks
        public async Task<IActionResult> Index()
        {
            var homeTaskContext = _context.ProductsInStock
                .Include(p => p.Product)
                .Include(p => p.Storage);
            return View(await homeTaskContext.ToListAsync());
        }
        
        public async Task<IActionResult> ShowProductsInStock(int? id)
        {
            var homeTaskContext = _context.ProductsInStock
                .Include(p => p.Product)
                .Include(p => p.Storage)
                .Where(stock => stock.StorageId == id);
            return View(await homeTaskContext.ToListAsync());
        }

        // GET: ProductsInStocks/Details/5
        public async Task<IActionResult> Details(int? productId, int? storageId)
        {
            if (productId == null && storageId == null) return NotFound();
            var productsInStock = await _context.ProductsInStock
                .Include(p => p.Product)
                .Include(p => p.Storage)
                .FirstOrDefaultAsync(m => m.StorageId == storageId);
            return productsInStock == null ? (IActionResult) NotFound() : View(productsInStock);
        }

        // GET: ProductsInStocks/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["StorageId"] = new SelectList(_context.Storages, "StorageId", "StorageName");
            return View();
        }

        // POST: ProductsInStocks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StorageId,ProductId,Count")] ProductsInStock productsInStock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productsInStock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["ProductId"] = new SelectList(
                _context.Products,
                "ProductId",
                "ProductName",
                productsInStock.ProductId
            );

            ViewData["StorageId"] = new SelectList(
                _context.Storages,
                "StorageId",
                "StorageName",
                productsInStock.StorageId
            );

            return View(productsInStock);
        }

        // GET: ProductsInStocks/Edit/5
        public  IActionResult Edit(int? productId, int? storageId)
        {
            if (productId == null && storageId == null) return NotFound();
            
            var productsInStock = _context.ProductsInStock.FirstOrDefault(stock =>
                stock.ProductId == productId && stock.StorageId == storageId);
            
            if (productsInStock == null) return NotFound();
            
            ViewData["ProductId"] = new SelectList(
                _context.Products, 
                "ProductId", 
                "ProductName",
                productsInStock.ProductId);
            
            ViewData["StorageId"] = new SelectList(
                _context.Storages, 
                "StorageId", 
                "StorageName",
                productsInStock.StorageId);
            
            return View(productsInStock);
        }

        // POST: ProductsInStocks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? productId, int? storageId, [Bind("StorageId,ProductId,Count")] ProductsInStock productsInStock)
        {
            if (storageId != productsInStock.StorageId && productId != productsInStock.ProductId) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productsInStock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return !ProductsInStockExists(productsInStock.StorageId)
                        ? (IActionResult) NotFound()
                        : RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["ProductId"] = new SelectList(
                _context.Products, 
                "ProductId", 
                "ProductName",
                productsInStock.ProductId);
            
            ViewData["StorageId"] = new SelectList(
                _context.Storages, 
                "StorageId", 
                "StorageName",
                productsInStock.StorageId);
            
            return View(productsInStock);
        }

        // GET: ProductsInStocks/Delete/5
        public async Task<IActionResult> Delete(int? productId, int? storageId)
        {
            if (productId == null && storageId == null) return NotFound();
            var productsInStock = await _context.ProductsInStock
                .Include(p => p.Product)
                .Include(p => p.Storage)
                .FirstOrDefaultAsync(m => m.StorageId == storageId);
            return productsInStock == null ? (IActionResult) NotFound() : View(productsInStock);
        }

        // POST: ProductsInStocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? productId, int? storageId)
        {
            var productsInStock =  _context.ProductsInStock.
                FirstOrDefault(stock => stock.StorageId == storageId && stock.ProductId == productId);
            if (productsInStock == null) return NotFound();
            _context.ProductsInStock.Remove(productsInStock);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ProductsInStockExists(int id)
        {
            return _context.ProductsInStock.Any(e => e.StorageId == id);
        }
    }
}

HomeTask/Controllers/StoragesController.cs
using System.Linq;
using System.Threading.Tasks;
using HomeTask.Controllers.UtilityControllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HomeTask.Models;
using HomeTask.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HomeTask.Controllers
{
    public class StoragesController : Controller
    {
        private readonly HomeTaskContext _context;

        public StoragesController(HomeTaskContext context)
        {
            _context = context;
        }

        // GET: Storages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Storages.ToListAsync());
        }

        // GET: Storages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var storage = await _context.Storages
                .FirstOrDefaultAsync(m => m.StorageId == id);
            return storage == null ? (IActionResult) NotFound() : View(storage);
        }

        // GET: Storages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Storages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StorageView storageView)
        {
            if (!ModelState.IsValid) return View(storageView);
            var storage = UtilityStorage.Create(storageView);
            _context.Add(storage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Storages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var storage = await _context.Storages.FindAsync(id);
            return storage == null ? (IActionResult) NotFound() : View(storage);
        }

        // POST: Storages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Storage storage)
        {
            if (id != storage.StorageId) return NotFound();
            if (!ModelState.IsValid) return View(storage);
            try
            {
                _context.Update(storage);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return !StorageExists(storage.StorageId) ? (IActionResult) NotFound() : RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Storages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var storage = await _context.Storages
                .FirstOrDefaultAsync(m => m.StorageId == id);
            return storage == null ? (IActionResult) NotFound() : View(storage);
        }

        // POST: Storages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var storage = await _context.Storages.FindAsync(id);
            _context.Storages.Remove(storage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult CalculateSum(int? id)
        {
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "CurrencyId", "CC");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CalculateSum(int? id, CalculateSumViewModel viewModel)
        {
            if (id == null) return NotFound();
            
            var productsInStock = await _context.ProductsInStock
                .Include(stock => stock.Product )
                .ToListAsync();
            
            if (productsInStock == null) return NotFound();
            
            foreach (var products in productsInStock.Where(products => products.StorageId == id))
            {
                viewModel.Sum += (products.Count * products.Product.BasicPrice);
            }
            
            var currency = _context.Currencies.FirstOrDefault(curr => curr.CurrencyId == viewModel.CurrencyId);
            if (currency == null) return NotFound();
            viewModel.Sum *= currency.Rate;  
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "CurrencyId", "CC");
            return View("SumResult", viewModel);
        }
        
        private bool StorageExists(int id)
        {
            return _context.Storages.Any(e => e.StorageId == id);
        }
    }
}

HomeTask/Views/Storages/CalculateSum.cshtml
@model HomeTask.ViewModels.CalculateSumViewModel

@{
    ViewData["Title"] = "CalculateSum";
}

<h1>CalculateSum</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CalculateSum">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CurrencyId" class="control-label"></label>
                <select asp-for="CurrencyId" class ="form-control" asp-items="ViewBag.CurrencyId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Calculate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HomeTask/Views/Storages/Create.cshtml
@model HomeTask.ViewModels.StorageView

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Storage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StorageName" class="control-label"></label>
                <input asp-for="StorageName" class="form-control" />
                <span asp-validation-for="StorageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HomeTask/Views/Storages/Delete.cshtml
@model HomeTask.Models.Storage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Storage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StorageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StorageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StorageId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HomeTask/Views/Storages/Details.cshtml
@model HomeTask.Models.Storage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Storage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StorageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StorageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StorageId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HomeTask/Views/Storages/Edit.cshtml
@model HomeTask.Models.Storage

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Storage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StorageId" />
            <div class="form-group">
                <label asp-for="StorageName" class="control-label"></label>
                <input asp-for="StorageName" class="form-control" />
                <span asp-validation-for="StorageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HomeTask/Views/Storages/Index.cshtml
@model IEnumerable<HomeTask.Models.Storage>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StorageName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StorageName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StorageId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StorageId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.StorageId">Delete</a> |
                <a asp-action="CalculateSum" asp-route-id="@item.StorageId">Calculate Sum</a> |
                <a asp-controller="ProductsInStocks" asp-action="ShowProductsInStock" asp-route-id="@item.StorageId">Show products in stock</a>
            </td>
        </tr>
}
    </tbody>
</table>

HomeTask/Views/Storages/SumResult.cshtml
@model HomeTask.ViewModels.CalculateSumViewModel
@{
    ViewData["Title"] = "Result";
}

<h1>Result</h1>

<div>
    <h4>Storage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sum)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>